addr: ':8080'
read_timeout: 10    # 读取超时时长
write_timeout: 10   # 写入超时时长
max_header_bytes: 20 # 最大的header大小，二进制位长度

mysql:
  user: 'root'
  password: 'root'
  host: '192.168.244.137'
  port: 3306
  dbname: 'blindbox'

wx:
  appid: 'wx7e1a5b4562d9d59e'
  secret: 'c438a24790fff29f29a4edad9ce601e3'
  grant_type: 'authorization_code'