addr: ':8080'
read_timeout: 10    # 读取超时时长
write_timeout: 10   # 写入超时时长
max_header_bytes: 20 # 最大的header大小，二进制位长度

mysql:
  user: 'root'
  password: 'root'
  host: '192.168.244.137'
  port: 3306
  dbname: 'blindbox'

wx:
  appid: 'wx7e1a5b4562d9d59e'
  secret: 'c438a24790fff29f29a4edad9ce601e3'
  grant_type: 'authorization_code'

redis:
  addr: '192.168.244.137:6379'
  password: 'youhe@@@520'
  db: 0

alioss:
  end_point: 'oss-cn-hangzhou.aliyuncs.com'
  access_key: 'LTAI4Fyc2WMmxFpWigqrY1kM'
  access_key_secret: '3lbGsC3RvOOb812qKgoeatVhMzmzYL'
  bucket: 'manhe-hcyj'
  base_url: 'https://manhe-hcyj.oss-cn-hangzhou.aliyuncs.com/'